pipeline{
    agent{
        label "any"
    }
    stages{
        stage("workspace"){
            steps{
                sh "pwd"
                sh "ls -la"
            }
        }
        stage("Build"){
            steps{
                echo "Building application..."
                sh "id"
                sh "date"
                sh "sleep 1"
            }
        }

        stage("Test"){
            steps{
                echo "Testing application..."
                sh "id"
                sh "date"
                sh "sleep 1"
            }
        }

        stage("Deploy"){
            steps{
                echo "Building application..."
                sh "id"
                sh "date"
                sh "sleep 1"
            }
        }
    }
}