pipeline{ 
    agent{
        label "any"
    }
    tools {
        go "1.21.1"
    }
    stages{
        stage("workspace"){
            steps{
                sh "pwd"
                sh "ls -la"
            }
        }
        stage("Build"){
            steps{
                echo "Building application..."
                sh "id"
                sh "date"
                sh "sleep 1"
                sh "go build simple-pipeline/hello-web.go"
            }
        }

        stage("Test"){
            steps{
                echo "Testing application..."
                sh "id"
                sh "date"
                sh "sleep 1"
                sh "go run simple-pipeline/hello-world.go"
                sh "./hello-web &"
                sh '''
                    #!/bin/bash
                    response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8081) &&
                    echo response is: $response
                    
                    if [[$response -eq 200]]
                    then
                      exit 0 
                    else
                      exit 1
                    fi'''
            }
        }

        stage("Deploy"){
            steps{
                echo "Building application..."
                sh "id"
                sh "date"
                sh "sleep 1"
            }
        }
    }
}